# The Thai Yelp Mythbuster and Food Recommender - Part 3

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

%matplotlib inline

## Review Modelling to find Best Thai Dishes in SF using ratings/sentiments

In [3]:
# reading the granular data-set with all the Thai restaurants and individual reviews
df = pd.read_csv('./yelp/yelp_thai_clean.csv')

In [4]:
# creating a master menu based on knowledge of Thai cuisine and based of most menus
sample_menu=[
'noodle soup','chicken noodle soup','beef noodle soup','noodles','pad see ew','pad kee mao','pad thai','fried rice','salad','papaya salad','papaya','chicken satay','satay','egg rolls','chicken','beef','fried chicken','roast duck','bbq pork','pork','roasted duck','panang curry','green curry','yellow curry','tom yum','tom kha','tom ka','thai iced tea','thai iced coffee',
'imperial rolls','angel wings','wings','corn cakes','mango salad','panang beef','curry','basa fillet','tofu','pumpkin curry','coconut ice cream',
'eggplant','fried banana','sticky rice','basil','pork belly','silver noodle','crab','calamari','cashew nut','fish cake','fish cakes','peanut sauce','samosa','catfish','pineapple fried rice','puff','money bag','money bags','silver noodle','pad see you','larb','quail','prawns','fried prawn','fried prawns','shrimp','seafood','salmon','ribs','chicken noodle','beef noodle','roti','pad cha','spring rolls','rolls','fried egg','imperial roll','spring roll','egg roll','tuna tower','volcanic beef','sea bass','crab cake',
'pad kee mow','massamam','lamb','drunken noodles','mango','coconut'
]

In [5]:
#just rating and review text
df = df[['rating', 'text']]

#switch to lower case
df.text = df.text.apply(lambda x: x.lower())

In [6]:
sample_menu = list(set(sample_menu))

#### Looking for dishes in sample menu and scoring them based on review-rating based on the average of the frequency they occur in the corpus - Scoring 1

In [7]:
# this returns just those reviews that have the word
# in the text of the review
def subset_reviews(word, df):
    return df[df.text.str.contains(word)]

# return avg rating of revies that contain dish
def avg_review_of_dish(item, df):
    return subset_reviews(item, df).mean()

# return nuber of times dishes reviewed
def dish_count(item, df):
    return subset_reviews(item, df).shape[0]

In [8]:
# create the dish review dataframe
dish_ratings = [avg_review_of_dish(item, df)[0] for item in sample_menu]
dish_counts = [dish_count(item, df) for item in sample_menu]
data = {'dish' : sample_menu,
       'rating' : dish_ratings,
       'times_reviewed': dish_counts}
dish_df = pd.DataFrame(data)

In [9]:
# dish review dataframe
dish_df[dish_df.times_reviewed > 99].sort_values(by = 'rating', ascending=False)

                    dish    rating  times_reviewed
8      coconut ice cream  4.057325             157
78           angel wings  4.025000             280
37          panang curry  3.973684             266
62                samosa  3.969925             133
73           sticky rice  3.959872             623
77          roasted duck  3.947368             114
12                 mango  3.944242             825
31          fried banana  3.943218             317
72                 wings  3.934783             690
58                  larb  3.889344             244
36                salmon  3.887967             241
52           green curry  3.853376             948
39               catfish  3.853333             150
20               coconut  3.846091            1228
75                 basil  3.840072            1113
21         thai iced tea  3.836991             638
79         pumpkin curry  3.828431             612
67                  lamb  3.825806             155
28              eggplant  3.806094             722
18                prawns  3.801310             458
27            pork belly  3.801075             186
23         chicken satay  3.792350             366
61          yellow curry  3.789400             717
47                 curry  3.777343            5111
49                  pork  3.769573            1124
44                 salad  3.750000            1948
84                  crab  3.747715             547
29                 satay  3.745543             617
54              calamari  3.737201             293
87          peanut sauce  3.725234             535
34           noodle soup  3.722433             526
13            fried rice  3.722287            1714
56  pineapple fried rice  3.717021             470
81                  ribs  3.714286             175
1           papaya salad  3.708879             687
17                 rolls  3.708529            1067
68                papaya  3.707692             715
4            pad kee mao  3.697460             433
59                  roti  3.689450             673
38               chicken  3.687500            4864
32               tom yum  3.677749             782
50             fish cake  3.666667             132
82            pad see ew  3.659760             917
48                tom ka  3.659218             179
63               tom kha  3.650000             400
69                  beef  3.649662            1627
19              egg roll  3.649038             208
5             roast duck  3.648855             131
60               seafood  3.648649             481
33             egg rolls  3.647727             176
76         fried chicken  3.647303             241
53          spring rolls  3.646154             520
24                  tofu  3.644413            1423
25              pad thai  3.635551            3246
46           spring roll  3.630508             590
30               noodles  3.568116            2070
3                 shrimp  3.530339            1269

#### Evaluating each review by scoring sentiment on the review for dishe rating - Scoring 2

In [10]:
# create sentiment df which is text, polarity of text
from textblob import TextBlob
df_sentiment = df[['text']]
df_sentiment.text = df_sentiment.text.apply(lambda x: x.lower())
df_sentiment['polarity'] = df_sentiment.text.apply(lambda x: TextBlob(x).sentiment.polarity)

C:\Users\dabhi\Anaconda3\lib\site-packages\pandas\core\generic.py:4401: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [11]:
# create the dish review dataframe
dish_ratings = [avg_review_of_dish(item, df_sentiment)[0] for item in sample_menu]
dish_counts = [dish_count(item, df_sentiment) for item in sample_menu]
data = {'dish' : sample_menu,
       'rating' : dish_ratings,
       'times_reviewed': dish_counts}
dish_df_sentiment = pd.DataFrame(data)

In [12]:
dish_df_sentiment[dish_df_sentiment.times_reviewed > 99].sort_values(by = 'rating', ascending=False)

                    dish    rating  times_reviewed
67                  lamb  0.267332             155
37          panang curry  0.255705             266
12                 mango  0.252410             825
8      coconut ice cream  0.248124             157
79         pumpkin curry  0.246930             612
31          fried banana  0.242966             317
77          roasted duck  0.241001             114
62                samosa  0.238047             133
78           angel wings  0.237894             280
73           sticky rice  0.237128             623
36                salmon  0.235200             241
21         thai iced tea  0.230788             638
39               catfish  0.229170             150
20               coconut  0.221162            1228
72                 wings  0.220969             690
4            pad kee mao  0.219813             433
17                 rolls  0.218821            1067
58                  larb  0.217760             244
84                  crab  0.216918             547
54              calamari  0.216766             293
1           papaya salad  0.214231             687
68                papaya  0.214030             715
44                 salad  0.213650            1948
53          spring rolls  0.212860             520
63               tom kha  0.212761             400
48                tom ka  0.212749             179
56  pineapple fried rice  0.212560             470
60               seafood  0.212358             481
18                prawns  0.212005             458
59                  roti  0.211789             673
46           spring roll  0.211272             590
47                 curry  0.209766            5111
28              eggplant  0.205099             722
34           noodle soup  0.204437             526
27            pork belly  0.204099             186
32               tom yum  0.203980             782
25              pad thai  0.203611            3246
24                  tofu  0.203262            1423
82            pad see ew  0.201941             917
87          peanut sauce  0.201552             535
75                 basil  0.201120            1113
69                  beef  0.199652            1627
5             roast duck  0.198675             131
49                  pork  0.198518            1124
13            fried rice  0.196612            1714
33             egg rolls  0.189895             176
81                  ribs  0.187221             175
50             fish cake  0.186744             132
3                 shrimp  0.185669            1269
19              egg roll  0.185159             208
30               noodles  0.184306            2070
52           green curry  0.182391             948
61          yellow curry  0.176788             717
29                 satay  0.160904             617
23         chicken satay  0.139216             366
38               chicken  0.126853            4864
76         fried chicken  0.105561             241

#### Granularly evaluating each review by scoring sentence sentiment as opposed to review sentiment for dishes - Scoring 3

In [13]:
# split the reviews into sentences
reviews_sentences = ''.join(list(df.text)).split('.')

# create a dataframe with these sentences
data = {'text' : reviews_sentences}
sentences_df = pd.DataFrame(data)
sentences_df.text = sentences_df.text.apply(lambda x: x.lower())

# create column which is polarity of text
from textblob import TextBlob
sentences_df['polarity'] = sentences_df.text.apply(lambda x: TextBlob(x).sentiment.polarity)

In [14]:
dish_ratings = [avg_review_of_dish(item, sentences_df)[0] for item in sample_menu]
dish_counts = [dish_count(item, sentences_df) for item in sample_menu]
data = {'dish' : sample_menu,
       'rating' : dish_ratings,
       'times_mentioned': dish_counts}
sentences_df = pd.DataFrame(data)

In [15]:
sentences_df[sentences_df.times_mentioned >=150].sort_values(by = 'rating', ascending=False)

                    dish    rating  times_mentioned
8      coconut ice cream  0.284138              176
31          fried banana  0.235810              357
21         thai iced tea  0.232521              698
67                  lamb  0.219962              207
79         pumpkin curry  0.200850              683
62                samosa  0.200051              158
12                 mango  0.197959             1055
59                  roti  0.192295              963
48                tom ka  0.182124              198
53          spring rolls  0.175485              592
60               seafood  0.175453              571
5             roast duck  0.174317              151
37          panang curry  0.174248              300
20               coconut  0.172838             1463
46           spring roll  0.172135              683
36                salmon  0.171464              306
54              calamari  0.169276              347
17                 rolls  0.166858             1268
73           sticky rice  0.164467              738
78           angel wings  0.163917              348
44                 salad  0.157218             2463
84                  crab  0.152185              687
1           papaya salad  0.151388              797
68                papaya  0.148728              849
32               tom yum  0.148542              915
87          peanut sauce  0.144967              619
63               tom kha  0.138865              447
34           noodle soup  0.138074              633
50             fish cake  0.130426              150
4            pad kee mao  0.128221              516
25              pad thai  0.125880             4150
30               noodles  0.125649             2655
82            pad see ew  0.123851             1086
39               catfish  0.120449              188
56  pineapple fried rice  0.120265              525
24                  tofu  0.119108             1736
58                  larb  0.116857              302
18                prawns  0.115974              558
47                 curry  0.115484             7039
27            pork belly  0.112114              247
81                  ribs  0.108461              227
49                  pork  0.104827             1474
28              eggplant  0.101817              857
69                  beef  0.099629             2034
3                 shrimp  0.099069             1551
13            fried rice  0.098360             2140
33             egg rolls  0.097902              199
75                 basil  0.097846             1351
19              egg roll  0.096565              237
72                 wings  0.095719              891
61          yellow curry  0.059271              817
52           green curry  0.000285             1107
29                 satay -0.053437              694
23         chicken satay -0.153570              393
38               chicken -0.173626             6956
76         fried chicken -0.204101              274

In [16]:
# Saving best Thai dishes in SF
# sentences_df.to_csv('./best_dishes.csv')

## Linear Regression Modelling to infer if beta coefficients are consistent with top dishes

In [17]:
#Creating new menu from previous data-set
new_menu = ['fish cake',
'roast duck',
'samosa',
'coconut ice cream',
'tom ka',
'egg rolls',
'ribs',
'egg roll',
'pork belly',
'fried chicken',
'panang curry',
'larb',
'salmon',
'calamari',
'angel wings',
'fried banana',
'chicken satay',
'tom kha',
'pad kee mao',
'pineapple fried rice',
'prawns',
'seafood',
'spring rolls',
'peanut sauce',
'noodle soup',
'pumpkin curry',
'spring roll',
'crab',
'satay',
'thai iced tea',
'sticky rice',
'papaya salad',
'yellow curry',
'papaya',
'eggplant',
'wings',
'tom yum',
'roti',
'mango',
'pad see ew',
'green curry',
'rolls',
'basil',
'coconut',
'pork',
'shrimp',
'tofu',
'beef',
'fried rice',
'salad',
'noodles',
'pad thai',
'chicken',
'curry']

In [18]:
def sentence_to_vector(sentence, menu):
    return [1*(dish in sentence) for dish in menu]

In [19]:
variable_sentences = [sentence_to_vector(sentence, new_menu) for sentence in reviews_sentences]

In [20]:
X = np.matrix(variable_sentences)
X.shape

(145598, 54)

In [21]:
y = [TextBlob(x).sentiment.polarity for x in reviews_sentences]
len(y)

145598

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [23]:
lr = LinearRegression()
lr.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [24]:
# Printing out beta coefficients
data = {'coef' : lr.coef_,
       'dish' : new_menu}
df = pd.DataFrame(data)
df.sort_values('coef', ascending=False)

        coef                  dish
29  0.095370         thai iced tea
23  0.078316          peanut sauce
4   0.072487                tom ka
2   0.070445                samosa
37  0.068342                  roti
41  0.063834                 rolls
38  0.060017                 mango
3   0.057275     coconut ice cream
15  0.055172          fried banana
43  0.049954               coconut
1   0.049734            roast duck
25  0.048192         pumpkin curry
13  0.045851              calamari
35  0.045664                 wings
17  0.044460               tom kha
42  0.043556                 basil
53  0.043512                 curry
21  0.038242               seafood
10  0.037636          panang curry
11  0.036968                  larb
34  0.034995              eggplant
49  0.034658                 salad
12  0.031973                salmon
31  0.031925          papaya salad
36  0.028028               tom yum
26  0.026592           spring roll
24  0.022862           noodle soup
51  0.022836              pad thai
0   0.018108             fish cake
39  0.016999            pad see ew
27  0.012589                  crab
18  0.011759           pad kee mao
28  0.010807                 satay
50  0.010432               noodles
48  0.006482            fried rice
14  0.003959           angel wings
19  0.003772  pineapple fried rice
6   0.002382                  ribs
20  0.001330                prawns
44 -0.001183                  pork
16 -0.004459         chicken satay
46 -0.005454                  tofu
30 -0.005782           sticky rice
8  -0.006897            pork belly
7  -0.013633              egg roll
47 -0.013947                  beef
45 -0.016772                shrimp
32 -0.026924          yellow curry
9  -0.027286         fried chicken
22 -0.036153          spring rolls
33 -0.038070                papaya
5  -0.060742             egg rolls
40 -0.130553           green curry
52 -0.353022               chicken

#### The beta coefficients are close to the top Thai dishes in San Francisco but inconsistent

In [25]:
# from sklearn.linear_model import LassoCV, Lasso
# from sklearn.model_selection import cross_val_score
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import make_pipeline

In [26]:
# def cv_r2(model):
#     r2 = np.mean(cross_val_score(model, X, y,scoring="r2",cv = 5))
#     return(r2)
# def lasso_selector(a):
#     lasso_model = make_pipeline(StandardScaler(),LassoCV(max_iter=1e7, alphas = [a],cv=5)).fit(X, y)
#     lasso_r2 = cv_r2(lasso_model).mean()
#     return(lasso_r2)
# lasso_alphas = [.0001, .0003, .0005, .0007, .0009,.01, 0.05, 0.1, 0.3, 1, 3, 5, 10, 15, 20, 30, 50, 100]
# lasso_scores = []
# for alpha in lasso_alphas:
#     score = lasso_selector(alpha)
#     lasso_scores.append(score)

In [27]:
# # Analyzing our Alphas
# plt.plot(lasso_alphas, lasso_scores, label='Lasso')
# lasso_score_table = pd.DataFrame(lasso_scores, lasso_alphas, columns=['R2'])
# lasso_score_table

In [28]:
# reg = Lasso(alpha = 0.0001)
# reg.fit(X,y)

In [29]:
# data = {'coef' : reg.coef_,
#        'dish' : new_menu}
# las_df = pd.DataFrame(data)
# las_df.sort_values('coef', ascending=False)

## Finding Top Dishes in Individual Restaurants

In [30]:
# recreating restaurant menu for finding top dishes in each restaurant
sample_menu_rest=[
'noodle soup','chicken noodle soup','beef noodle soup','pad see ew','pad kee mao','pad thai','fried rice','salad','papaya salad','satay','egg rolls','chicken','beef','fried chicken','roast duck','bbq pork','pork','roasted duck','panang curry','green curry','yellow curry','tom yum','tom kha','tom ka','thai iced tea','thai iced coffee',
'imperial rolls','angel wings','wings','corn cakes','mango salad','panang beef','curry','basa fillet','tofu','pumpkin curry','coconut ice cream',
'fried banana','sticky rice','pork belly','silver noodle','crab','calamari','fish cake','fish cakes','peanut sauce','samosa','catfish','pineapple fried rice','money bag','money bags','silver noodle','pad see you','larb','quail','prawns','fried prawn','fried prawns','shrimp','seafood','salmon','ribs','chicken noodle','beef noodle','roti','pad cha','spring rolls','fried egg','imperial roll','spring roll','egg roll','tuna tower','volcanic beef','sea bass','crab cake',
'pad kee mow','massamam','lamb','drunken noodles'   
]

In [31]:
# creating a restaurant function which takes in name of the restaurant and returns top 10 dishes
def restaurant_food(a):
    df = pd.read_csv('./yelp/yelp_thai_clean.csv')
    #restrict to a Thai restaurant
    df = df[df.restaurant == a]

    #just grab rating and review text
    df = df[['rating', 'text']]

    #switch to lower case
    df.text = df.text.apply(lambda x: x.lower())
    
    # this returns just those reviews that have the word
    # in the text of the review
    def subset_reviews(word, df):
        return df[df.text.str.contains(word)]

    # return avg rating of revies that contain dish
    def avg_review_of_dish(item, df):
        return subset_reviews(item, df).mean()

    # return nuber of times dishes reviewed
    def dish_count(item, df):
        return subset_reviews(item, df).shape[0]
    # split the reviews into sentences
    reviews_sentences = ''.join(list(df.text)).split('.')

    # create a dataframe with these sentences
    data = {'text' : reviews_sentences}
    sentences_df = pd.DataFrame(data)
    sentences_df.text = sentences_df.text.apply(lambda x: x.lower())

    # create column which is polarity of text
    from textblob import TextBlob
    sentences_df['polarity'] = sentences_df.text.apply(lambda x: TextBlob(x).sentiment.polarity)
    
    dish_ratings = [avg_review_of_dish(item, sentences_df)[0] for item in sample_menu_rest]
    dish_counts = [dish_count(item, sentences_df) for item in sample_menu_rest]
    data = {'dish' : sample_menu_rest,
           'rating' : dish_ratings,
           'times_mentioned': dish_counts}
    sentences_df = pd.DataFrame(data)
    return sentences_df[sentences_df.times_mentioned >=9].sort_values(by = 'rating', ascending=False).head(10)

In [32]:
# finding the best dishes in an individual restaurant
restaurant_food("Osha Thai")

             dish    rating  times_mentioned
72  volcanic beef  0.341867               24
71     tuna tower  0.339284               22
39     pork belly  0.297829               11
21        tom yum  0.250101               21
24  thai iced tea  0.237322               29
38    sticky rice  0.229123               15
59        seafood  0.198861               19
6      fried rice  0.190993               70
60         salmon  0.189683               21
35  pumpkin curry  0.183295               36

In [33]:
# finding the best dishes in an individual restaurant
restaurant_food("Marnee Thai")

                 dish    rating  times_mentioned
17       roasted duck  0.346962               12
26     imperial rolls  0.314263               13
68      imperial roll  0.314263               13
64               roti  0.301287               24
36  coconut ice cream  0.297135               16
46             samosa  0.277990               22
69        spring roll  0.268089                9
42           calamari  0.267397               15
24      thai iced tea  0.262864               26
29         corn cakes  0.260882               17